version: "3.3"
services:
  db:
    build: ./docker/postgres-eucjp
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: "--encoding=EUC_JP --lc-collate=C --lc-ctype=ja_JP.eucJP"
      POSTGRES_DB: sample_db
      POSTGRES_HOST_AUTH_METHOD: trust
      # required set user & password
      # POSTGRES_USER: user
      # POSTGRES_PASSWORD: password
    command: 'postgres -c config_file="/etc/postgresql/postgresql.conf"'
    ports:
      - "5432:5432"
    volumes:
      # - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgres-eucjp/conf.d:/etc/postgresql
      - ./log/postgres:/var/log/postgres-eucjp
